#!/usr/bin/env python3
"""schemas.lock.yaml に記載されたサービスごとの DDL を取得し、union SQL を構築します。

CI (GitHub Actions runner) 上で docker build 前に実行される。各サービスリポジトリを
sparse-checkout でクローンし、lock ファイルに固定された ref のスキーマファイルのみ取得する。
結合結果は db-migrate/sql/schema_union.sql に書き出され、psqldef が適用する。

fetch を Docker 外で行う理由:
  - Git 認証は workflow (DB_MIGRATE_TOKEN secret) にあり、イメージに含めない
  - sql/ の COPY レイヤーハッシュでキャッシュが効くため PAT を中間レイヤーに含めない
  - 旧スキーマとの差分チェックもイメージ外の方が容易

引数:
  --lock PATH          schemas.lock.yaml パス (デフォルト: db-migrate/schemas.lock.yaml)
  --out  PATH          union 出力ファイル (デフォルト: db-migrate/sql/schema_union.sql)
  --workdir DIR        クローン用作業ディレクトリ (デフォルト: /tmp/schema-src)
  --token TOKEN        GitHub PAT (環境変数 GITHUB_TOKEN / DB_MIGRATE_TOKEN fallback)
  --ref-override REF   全エントリを強制的にこの ref に上書き (CI dispatch override)
"""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

# schemas.lock.yaml から取得したスキーマ名がファイルパスや SQL に到達する前に
# バリデーションするための PostgreSQL unquoted identifier ルール。
# 不正な値（例: `../etc/passwd` や `foo; DROP SCHEMA`）を即座に弾く。
_SCHEMA_NAME_RE = re.compile(r"^[a-z_][a-z0-9_]*$")


def _validate_schema_name(schema_name: str, *, source: str) -> None:
    """スキーマ名が PostgreSQL unquoted identifier ルールに適合するか検証します。"""
    if not isinstance(schema_name, str) or not _SCHEMA_NAME_RE.match(schema_name):
        raise SystemExit(
            f"ERROR: invalid schema name {schema_name!r} ({source}). "
            "Must match PostgreSQL unquoted identifier rules: ^[a-z_][a-z0-9_]*$"
        )


def _load_yaml(path: Path) -> dict:
    """YAML ファイルを読み込みます。"""
    import yaml  # type: ignore
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _run(cmd: list[str], cwd: Path | None = None) -> None:
    """外部コマンドを実行します。"""
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, check=True)


def _clone_sparse(repo: str, ref: str, file_path: str, dest: Path, token: str | None) -> Path:
    """GitHub リポジトリから単一ファイルを shallow sparse-clone します。"""
    dest.mkdir(parents=True, exist_ok=True)

    if token:
        url = f"https://x-access-token:{token}@github.com/{repo}.git"
    else:
        url = f"https://github.com/{repo}.git"

    try:
        _run(["git", "init", "-q"], cwd=dest)
        _run(["git", "remote", "add", "origin", url], cwd=dest)
        _run(["git", "config", "core.sparseCheckout", "true"], cwd=dest)
        sparse_file = dest / ".git" / "info" / "sparse-checkout"
        sparse_file.parent.mkdir(parents=True, exist_ok=True)
        sparse_file.write_text(file_path + "\n", encoding="utf-8")
        _run(["git", "fetch", "--depth=1", "origin", ref], cwd=dest)
        _run(["git", "checkout", "FETCH_HEAD"], cwd=dest)
    except subprocess.CalledProcessError as e:
        raise SystemExit(
            f"ERROR: git operation failed for schemas.lock.yaml entry "
            f"{repo}@{ref}:{file_path} (exit {e.returncode}). "
            f"Check that the repo / ref exists and DB_MIGRATE_TOKEN has read access."
        ) from e

    target = dest / file_path
    if not target.is_file():
        raise SystemExit(
            f"ERROR: expected file {file_path} not found in {repo}@{ref}. "
            f"schemas.lock.yaml entry is stale."
        )
    return target


def build_union(lock: dict, workdir: Path, token: str | None, ref_override: str | None) -> str:
    """全サービスの DDL を取得・結合して union SQL を構築します。"""
    if "schemas" not in lock or not isinstance(lock["schemas"], list):
        raise SystemExit("ERROR: schemas.lock.yaml must contain a `schemas:` list")

    chunks: list[str] = []
    banner = "-- " + "=" * 77

    chunks.append(banner)
    chunks.append("-- schema_union.sql — generated by db-migrate/fetch-schemas.py")
    chunks.append("-- DO NOT EDIT. Edit schemas.lock.yaml and re-run the migration workflow.")
    chunks.append(banner)
    chunks.append("")

    for entry in lock["schemas"]:
        name = entry["name"]
        repo = entry["repo"]
        path = entry["path"]
        ref = ref_override or entry.get("ref", "main")

        # `name` はスクラッチディレクトリ名と union SQL のバナーに使われる。
        # PostgreSQL identifier でない値はロックファイル改竄として即座に中断する
        # （パストラバーサルやシェルメタ文字に対する多重防御）。
        _validate_schema_name(name, source=f"schemas.lock.yaml entry for repo={repo!r}")

        print(f"==> fetching {name}: {repo}@{ref}:{path}", flush=True)
        dest = workdir / name
        if dest.exists():
            _run(["rm", "-rf", str(dest)])
        sql_path = _clone_sparse(repo, ref, path, dest, token)
        sql = sql_path.read_text(encoding="utf-8")

        chunks.append(banner)
        chunks.append(f"-- [{name}]  source: {repo}@{ref}  path: {path}")
        chunks.append(banner)
        chunks.append(sql.rstrip() + "\n")

    return "\n".join(chunks) + "\n"


def main() -> int:
    """スキーマ取得・結合のメインエントリーポイントです。"""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--lock", default="db-migrate/schemas.lock.yaml")
    ap.add_argument("--out", default="db-migrate/sql/schema_union.sql")
    ap.add_argument("--grant-src", default="db-migrate/grant_iam.sql",
                    help="Canonical grant_iam.sql path (committed in ops repo). "
                         "Copied alongside the union so Dockerfile COPY sql/ picks up both.")
    ap.add_argument("--workdir", default="/tmp/schema-src")
    ap.add_argument("--token", default=None)
    ap.add_argument("--ref-override", default=None)
    args = ap.parse_args()

    token = args.token or os.environ.get("GITHUB_TOKEN") or os.environ.get("DB_MIGRATE_TOKEN")
    lock = _load_yaml(Path(args.lock))

    workdir = Path(args.workdir)
    workdir.mkdir(parents=True, exist_ok=True)

    union = build_union(lock, workdir, token, args.ref_override)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(union, encoding="utf-8")
    print(f"==> wrote {out} ({len(union)} bytes, {union.count(chr(10))} lines)")

    # sql/ は gitignore されているビルド成果物ディレクトリ。Dockerfile の
    # `COPY sql/ /app/sql/` が union / grant_iam 両方を拾えるよう、コミット済みの
    # grant_iam.sql を同じディレクトリにステージする。
    grant_src = Path(args.grant_src)
    if not grant_src.is_file():
        raise SystemExit(f"ERROR: grant_iam.sql not found at {grant_src}")
    grant_dst = out.parent / "grant_iam.sql"
    grant_dst.write_bytes(grant_src.read_bytes())
    print(f"==> staged {grant_dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
